### ISSUE TITLE
More explicit and better pipe-support

### ISSUE THREAD

**Issue by mk13** [dart-lang/angular_ast#43]
Potentially look into desugaring/expression parsing pattern with pipes.

**Comment by MichaelRFairhurst** [comment]
Currently I think it does mostly what the analyzer does, but instead of turning `x | y` into `x as dynamic` (which helps us bail out of analysis), it turns it into `$ngPipe.y(x)`, which makes our analysis harder.

I think if we solve this at the angular_ast level, we want to make `class PipeExpression extends dart.Expression`, and `AngularDartVisitor extends DartVisitor { void visitPipeExpression() }`.

That way we can both use visitors to do what we need in a generic way, without having to do things like "check all functions on objects named $ngPipe". Especially if the visitor for the compiler can just turn `PipeExpression`s into `$ngPipe.x(y)`, letting them keep that easy-for-them worklfow.

This will also be useful for when we do in the future want to analyze `x | y`, so turning it into `x as dynamic` throws away valuable information anyway.

**Comment by mk13** [comment]
Resolved for now - but may have to revisit once changes on the Parser occur by @danrubel
